version: "3.9"

services:
  db:
    image: postgres
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=1991
        - POSTGRES_DB=postgres
    ports:
        - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL","pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  api:
    build:
      context: .
    tty : false
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
    driver: local